package com.pzbapps.squiggly.common.domain.utils

object Constant {

    const val SUCCESS = "SUCCESS"
    const val FAILURE = "FAILURE"
    const val USER_KEY = "LoggedInUser"
    const val USER_VALUE = "User"
    const val SHARED_PREP_NAME = "rememberUser"
    const val ARCHIVE = "archive"
    const val HOME = "home"
    const val LOCKED_NOTE = "locked_note"
    const val TRIAL_ENDED = "trial_ended"
    const val TRIAL_ONGOING = "trial_ongoing"
    const val TRIAL_NOT_STARTED = "trial_not_started"
    const val TRIAL_ENDED_OR_NOT = "trial_ended_or_not"
    const val NOT_CATEGORIZED = "Not Categorized"
    const val LIST_PREFERENCE = "list_preference"
    const val LIST_OR_GRID = "list_or_grid"
    const val CHANGE_THEME = "change_theme"
    const val THEME_KEY = "theme_key"
    const val SYSTEM_DEFAULT = "system_default"
    const val DARK_THEME = "dark_theme"
    const val LIGHT_THEME = "light_theme"
    const val AUTO_SAVE_PREF = "auto_save_pref"
    const val AUTO_SAVE_KEY = "auto_save_key"
    const val AUTO_SAVE_PREF_EVERY_24_HOURS = "auto_save_pref_every_24_hours"
    const val AUTO_SAVE_KEY_EVERY_24_HOURS = "auto_save_key_every_24_hours"
    const val SORT_ORDER = "sort_order"
    const val SORT_ORDER_KEY = "sort_order_key"
    const val SORT_ORDER_VALUE_1 = "created date"
    const val SORT_ORDER_VALUE_2 = "modified date"
    const val SHOW_RATING_DIALOG_BOX = "show_rating_dialog_box"
    const val SHOW_RATING_DIALOG_BOX_KEY = "show_rating_dialog_box_key"
    const val HIDE_RATING_DIALOG_BOX = "hide_rating_dialog_box"
    const val HIDE_RATING_DIALOG_BOX_KEY = "hide_rating_dialog_box_key"
    const val  SHOW_PREMIUM_PLANS = "show_premium_plans"
    const val SHOW_PREMIUM_PLANS_KEY  = "show_premium_plans_key"

}